### ISSUE TITLE
missing data key

### ISSUE THREAD

**Issue by amirhabib** [YanaMKL/FinalProject#10]
the response should be like this:

{
 success: boolean, 
 **data**: [ 
 {    id: number (int),
   name: string,      
   categoryId: number (int),
   price: number (int),    
   imageUrl: string  },
 { item 2 },
 { item 3 },
 { … }
  ]
}

https://github.com/YanaMKL/FinalProject/blob/9f5edabf041262d70e541aa438922ba6aed7ae90/store.js#L79

**Comment by YanaMKL** [comment]
לא כל כך מובן לי איך אני מציגה ברספונס מערך....

**Comment by amirhabib** [comment]
הבעיה זו לא המערך אלא שחסר לך השדה דטה
רשמת משהו אחר במקום
וכדאי לבדוק כמה רשומות חזרו, אם יש יותר מאחד, סביר שהם חוזרים כמערך כבר
הבעיה יכולה להיות כשיש רק מוצר אחד, או אין מוצרים, צריך עדיין לוודא שיהיה מערך
קודם כל מציע לך לבדוק מצב שיש יותר ממוצר אחד, ולראות אם מקבל מערך באופן אוטומטי
ואם כן, בודקים מה קורה שיש רק מוצר אחד, האם עדיין מתקבל מערך אוטומטי?
