### ISSUE TITLE
חסר תיאור השגיאה

### ISSUE THREAD

**Issue by amirhabib** [YanaMKL/FinalProject#5]
כסקסס הוא פולס
יוצאים מנקודת הנחה שיש שדה ארר, שהוא צריך להכיל שדה שמתאר את הבעיה

err.message: 'id is missing'

https://github.com/YanaMKL/FinalProject/blob/5a9c87615e56e792cfb12cf04e16ba4bf7eda661/store.js#L43

**Comment by YanaMKL** [comment]
done
