### ISSUE TITLE
We don't want to throw the error - just return response

### ISSUE THREAD

**Issue by amirhabib** [YanaMKL/FinalProject#9]
If you throw an error, it means you want some process (on nodejs) to take care of that error or otherwise EXIT the program.

We don't need it here. All we need is in case of error - we return:

{
   success: false,
   err: 'some error message'
}

or 

{
 success: false
}

the first options is always better.

https://github.com/YanaMKL/FinalProject/blob/9f5edabf041262d70e541aa438922ba6aed7ae90/store.js#L54

**Comment by YanaMKL** [comment]
ככה????

{
success: false,
 'some error message'
}

or

{
success: false
}

**Comment by amirhabib** [comment]
העיקר שלא יהיה 
throw err 
זה יגרום לשרת לעצור
